// @flow
import * as React from 'react';
import TestRenderer from 'react-test-renderer';
import {
  getAiRequest,
  getAiRequestStatuses,
  fetchAiSettings,
  getAiRequestSummaries,
  getAiRequestSummary,
  suspendAiRequest,
  updateAiRequest as apiUpdateAiRequest,
  deleteAiRequest as apiDeleteAiRequest,
  type AiRequest,
  type AiRequestSummary,
  type AiRequestUserMessage,
} from '../Utils/GDevelopServices/Generation';
import {
  customGetAiRequest,
  setCustomEndpointConfig,
} from '../AI/CustomAIClient';
import { type AuthenticatedUser } from '../Profile/AuthenticatedUserContext';
import AuthenticatedUserContext, {
  initialAuthenticatedUser,
} from '../Profile/AuthenticatedUserContext';
import {
  AiRequestContext,
  AiRequestProvider,
  mergeIncrementalAiRequest,
  useAiRequestHistory,
  type AiRequestContextState,
} from './AiRequestContext';
import { act } from 'react-dom/test-utils';

jest.mock('../Utils/GDevelopServices/Generation', () => ({
  ...jest.genMockFromModule('../Utils/GDevelopServices/Generation'),
  // A pure helper: the summary of a request is built for real.
  getAiRequestSummary: jest.requireActual<any>(
    '../Utils/GDevelopServices/Generation'
  ).getAiRequestSummary,
}));

const mockFn = (fn: any): JestMockFn<any, any> => fn;

const POLLING_INTERVAL_IN_MS = 1400;
// After an idle tick the adaptive polling interval backs off ×1.5 (see
// useAdaptivePollingInterval), so later ticks fire after a longer delay.
const POLLING_INTERVAL_AFTER_BACKOFF_IN_MS = Math.round(
  POLLING_INTERVAL_IN_MS * 1.5
); // 2100
const POLLING_INTERVAL_AFTER_2X_BACKOFF_IN_MS = Math.round(
  POLLING_INTERVAL_AFTER_BACKOFF_IN_MS * 1.5
); // 3150

const makeAiRequest = (
  id: string,
  status: 'working' | 'ready' | 'error' | 'suspended',
  parentAiRequestId?: string | null
): AiRequest => ({
  id,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  userId: 'user-1',
  status,
  error: null,
  output: [],
  parentAiRequestId: parentAiRequestId || null,
});

const makeAuthenticatedUser = (): AuthenticatedUser => ({
  ...initialAuthenticatedUser,
  authenticated: true,
  profile: {
    id: 'user-1',
    email: 'fake@example.com',
    username: 'fake-user',
    isEmailAutogenerated: false,
    description: '',
    getGameStatsEmail: false,
    getNewsletterEmail: false,
    isCreator: false,
    isPlayer: false,
    appLanguage: 'en',
    donateLink: null,
    discordUsername: null,
    communityLinks: {},
    createdAt: 0,
    updatedAt: 0,
  },
  loginState: 'done',
  getAuthorizationHeader: () => Promise.resolve('fake-auth-header'),
});

const makeLoggedOutUser = (): AuthenticatedUser => ({
  ...initialAuthenticatedUser,
  authenticated: false,
  profile: null,
  loginState: 'done',
  getAuthorizationHeader: () => Promise.resolve(''),
});

const ContextCapture = ({
  contextRef,
}: {|
  contextRef: { current: AiRequestContextState | null },
|}) => {
  const context = React.useContext(AiRequestContext);
  contextRef.current = context;
  return null;
};

const flushPromises = async () => {
  // Allow chained promises inside the polling tick to resolve.
  // The tick performs several `await`s sequentially, so we flush a few times.
  for (let i = 0; i < 10; i++) {
    // eslint-disable-next-line no-await-in-loop
    await Promise.resolve();
  }
};

const renderProvider = (authenticatedUser?: AuthenticatedUser) => {
  const contextRef: { current: AiRequestContextState | null } = {
    current: null,
  };
  const user = authenticatedUser || makeAuthenticatedUser();
  let renderer;
  act(() => {
    renderer = TestRenderer.create(
      <AuthenticatedUserContext.Provider value={user}>
        <AiRequestProvider>
          <ContextCapture contextRef={contextRef} />
        </AiRequestProvider>
      </AuthenticatedUserContext.Provider>
    );
  });
  return { contextRef, renderer };
};

describe('AiRequestProvider sub-agent polling', () => {
  beforeEach(() => {
    jest.useFakeTimers();
    mockFn(getAiRequest).mockReset();
    mockFn(getAiRequestStatuses).mockReset();
    mockFn(getAiRequestStatuses).mockResolvedValue([]);
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequestSummaries).mockReset();
    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [],
      nextPageUri: null,
    });
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  // Covers bug 2 fix: once the sub-agent is in a non-`working` state, the
  // (batched) status-only polling that returns the same status must NOT trigger
  // additional full fetches. Previously the code compared the status against the
  // hardcoded `'working'` and full-fetched on every tick afterward.
  it('does not spam full fetches while a sub-agent stays in `ready` state', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    const subAgentReady = makeAiRequest('sub-1', 'ready');
    mockFn(getAiRequest).mockResolvedValue(subAgentReady);
    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'sub-1', status: 'ready', userId: 'user-1' },
    ]);

    // Seed the sub-agent in the storage and mark it as active so the polling
    // loop picks it up.
    await act(async () => {
      // $FlowFixMe[incompatible-use] - contextRef.current is set above.
      contextRef.current.aiRequestStorage.updateAiRequest(
        'sub-1',
        () => subAgentReady
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-1', 'parent-1', 'call-1');
    });

    // First tick: shouldDoFullFetch is true (lastFullFetch starts at 0).
    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);
    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(0);

    // Subsequent ticks within the full-fetch window do a (batched) status-only
    // fetch only. Because the status matches the cached status, no additional
    // full fetch should happen. The interval backs off after each idle tick, so
    // advance by the backed-off amount to fire each tick (still within the 7s
    // window: 1400 + 2100 + 3150 = 6650ms).
    for (const intervalMs of [
      POLLING_INTERVAL_AFTER_BACKOFF_IN_MS,
      POLLING_INTERVAL_AFTER_2X_BACKOFF_IN_MS,
    ]) {
      // eslint-disable-next-line no-await-in-loop
      await act(async () => {
        jest.advanceTimersByTime(intervalMs);
        await flushPromises();
      });
    }

    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(2);
    // Critical assertion: still only the initial full fetch — the bug
    // would have caused one full fetch per tick after the sub-agent
    // reached `ready`.
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);
  });

  // Covers bug 2 fix from the opposite angle: a real status change *must*
  // still trigger an immediate full fetch.
  it('triggers a full fetch immediately when the batched status fetch reports a status change', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    const subAgentWorking = makeAiRequest('sub-1', 'working');
    const subAgentReady = makeAiRequest('sub-1', 'ready');

    // Cached status starts as 'working'.
    mockFn(getAiRequest).mockResolvedValue(subAgentWorking);

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'sub-1',
        () => subAgentWorking
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-1', 'parent-1', 'call-1');
    });

    // First tick consumes the initial full fetch.
    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);

    // Now backend switches the sub-agent to `ready`. The batched status fetch
    // reports the new status, so the polling loop should immediately do another
    // full fetch even though the full-fetch window has not elapsed.
    mockFn(getAiRequest).mockResolvedValue(subAgentReady);
    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'sub-1', status: 'ready', userId: 'user-1' },
    ]);

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_AFTER_BACKOFF_IN_MS);
      await flushPromises();
    });

    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(1);
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(2);
  });

  // The selected parent and all its active sub-agents are status-polled in a
  // single batched request per tick.
  it('batches the parent and all sub-agents into a single status request', async () => {
    const { contextRef } = renderProvider();
    const context = contextRef.current;
    if (!context) throw new Error('Context not captured');

    mockFn(getAiRequest).mockImplementation((_, { aiRequestId }) =>
      Promise.resolve(makeAiRequest(aiRequestId, 'working'))
    );

    await act(async () => {
      context.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-1', () =>
        makeAiRequest('sub-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-2', () =>
        makeAiRequest('sub-2', 'working')
      );
      context.setSelectedAiRequestId('parent-1');
      context.activateSubAgent('sub-1', 'parent-1', 'call-1');
      context.activateSubAgent('sub-2', 'parent-1', 'call-2');
    });

    // First tick: everyone is due for a full fetch.
    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });

    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'parent-1', status: 'working', userId: 'user-1' },
      { id: 'sub-1', status: 'working', userId: 'user-1' },
      { id: 'sub-2', status: 'working', userId: 'user-1' },
    ]);

    // Second tick: everyone is status-only → one batched request for all ids.
    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_AFTER_BACKOFF_IN_MS);
      await flushPromises();
    });

    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(1);
    expect(
      mockFn(getAiRequestStatuses).mock.calls[0][1].aiRequestIds.sort()
    ).toEqual(['parent-1', 'sub-1', 'sub-2']);
  });

  // When the batched response reports a single change, only that entity is
  // full-fetched; the unchanged ones are not.
  it('only full-fetches the entity whose status changed', async () => {
    const { contextRef } = renderProvider();
    const context = contextRef.current;
    if (!context) throw new Error('Context not captured');

    mockFn(getAiRequest).mockImplementation((_, { aiRequestId }) =>
      Promise.resolve(makeAiRequest(aiRequestId, 'working'))
    );

    await act(async () => {
      context.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-1', () =>
        makeAiRequest('sub-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-2', () =>
        makeAiRequest('sub-2', 'working')
      );
      context.setSelectedAiRequestId('parent-1');
      context.activateSubAgent('sub-1', 'parent-1', 'call-1');
      context.activateSubAgent('sub-2', 'parent-1', 'call-2');
    });

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(3);

    // Only sub-1 changes; parent and sub-2 stay working.
    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'parent-1', status: 'working', userId: 'user-1' },
      { id: 'sub-1', status: 'ready', userId: 'user-1' },
      { id: 'sub-2', status: 'working', userId: 'user-1' },
    ]);

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_AFTER_BACKOFF_IN_MS);
      await flushPromises();
    });

    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(1);
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(4);
    expect(mockFn(getAiRequest).mock.calls[3][1].aiRequestId).toBe('sub-1');
  });

  // An id missing from the batched response (not found / not yet visible) must
  // be left as-is, without crashing or triggering a full fetch.
  it('leaves an entity untouched when it is missing from the batched response', async () => {
    const { contextRef } = renderProvider();
    const context = contextRef.current;
    if (!context) throw new Error('Context not captured');

    mockFn(getAiRequest).mockImplementation((_, { aiRequestId }) =>
      Promise.resolve(makeAiRequest(aiRequestId, 'working'))
    );

    await act(async () => {
      context.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-1', () =>
        makeAiRequest('sub-1', 'working')
      );
      context.setSelectedAiRequestId('parent-1');
      context.activateSubAgent('sub-1', 'parent-1', 'call-1');
    });

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(2);

    // sub-1 is omitted from the response.
    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'parent-1', status: 'working', userId: 'user-1' },
    ]);

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_AFTER_BACKOFF_IN_MS);
      await flushPromises();
    });

    const updated = contextRef.current;
    if (!updated) throw new Error('Context not captured');
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(2);
    expect(Object.keys(updated.activeSubAgents)).toEqual(['sub-1']);
  });
});

describe('AiRequestProvider sub-agent cleanup on navigation', () => {
  beforeEach(() => {
    jest.useFakeTimers();
    mockFn(getAiRequest).mockReset();
    mockFn(getAiRequestStatuses).mockReset();
    mockFn(getAiRequestStatuses).mockResolvedValue([]);
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequestSummaries).mockReset();
    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [],
      nextPageUri: null,
    });
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  // Covers bug 3 fix: when the user switches away from a parent AI request,
  // its sub-agents must be removed from the active map so they stop polling.
  // Previously the cleanup only ran when the parent transitioned to
  // `suspended`, leaving sub-agents to poll forever after a navigation.
  it('removes sub-agents of the previously selected request when selection changes', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'ready')
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest('parent-2', () =>
        makeAiRequest('parent-2', 'ready')
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
    });

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-1', 'parent-1', 'call-1');
    });

    // $FlowFixMe[incompatible-use]
    expect(Object.keys(contextRef.current.activeSubAgents)).toEqual(['sub-1']);

    // Switching to another parent must trigger the cleanup effect of the
    // previous selection and drop its sub-agent.
    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-2');
    });

    // $FlowFixMe[incompatible-use]
    expect(contextRef.current.activeSubAgents).toEqual({});
  });

  // Same fix: navigating away from a parent (no selection at all) must also
  // drop its sub-agents.
  it('removes sub-agents when the selected request is cleared', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'ready')
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
    });

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-a', 'parent-1', 'call-a');
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-b', 'parent-1', 'call-b');
    });

    // $FlowFixMe[incompatible-use]
    expect(Object.keys(contextRef.current.activeSubAgents).sort()).toEqual([
      'sub-a',
      'sub-b',
    ]);

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId(null);
    });

    // $FlowFixMe[incompatible-use]
    expect(contextRef.current.activeSubAgents).toEqual({});
  });

  // Sub-agents whose parent is *not* the previously selected request must
  // not be affected when the selection changes — guards against an overzealous
  // cleanup that would also drop them.
  it('only removes sub-agents whose parent matches the previously selected request', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'ready')
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
    });

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-1', 'parent-1', 'call-1');
      // A sub-agent that belongs to a different parent (e.g. one not
      // currently displayed) - the cleanup must leave it alone.
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-2', 'parent-other', 'call-2');
    });

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId(null);
    });

    // $FlowFixMe[incompatible-use]
    expect(Object.keys(contextRef.current.activeSubAgents)).toEqual(['sub-2']);
  });
});

describe('AiRequestProvider offline BYOK watch (no profile)', () => {
  beforeEach(() => {
    jest.useFakeTimers();
    mockFn(getAiRequest).mockReset();
    mockFn(getAiRequestStatuses).mockReset();
    mockFn(getAiRequestStatuses).mockResolvedValue([]);
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequestSummaries).mockReset();
    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [],
      nextPageUri: null,
    });
    setCustomEndpointConfig({
      enabled: true,
      baseUrl: 'http://localhost:11434/v1',
      apiKey: '',
      model: 'qwen2.5-coder',
      temperature: 0.7,
    });
  });

  afterEach(() => {
    setCustomEndpointConfig({
      enabled: false,
      baseUrl: 'http://localhost:11434/v1',
      apiKey: '',
      model: 'qwen2.5-coder',
      temperature: 0.7,
    });
    jest.useRealTimers();
  });

  // Offline studio: onWatch used to early-return on !profile, so finished
  // sub-agents were never retired and hasActiveSubAgents kept the chat input
  // disabled forever. Local BYOK watches must run without a profile.
  it('retires a finished sub-agent when logged out with the custom endpoint enabled', async () => {
    const { contextRef } = renderProvider(makeLoggedOutUser());
    if (!contextRef.current) throw new Error('Context not captured');

    const parentWithOutput = {
      ...makeAiRequest('parent-1', 'ready'),
      output: [
        {
          type: 'function_call_output',
          call_id: 'call-1',
          output: 'done',
        },
      ],
    };
    const subReady = makeAiRequest('local-ai-sub-1', 'ready');
    mockFn(getAiRequest).mockResolvedValue(subReady);

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'parent-1',
        () => parentWithOutput
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'local-ai-sub-1',
        () => subReady
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent(
        'local-ai-sub-1',
        'parent-1',
        'call-1'
      );
    });

    // Selection is cleared by the !profile effect only when profile *changes*;
    // re-assert selection after that effect has already run on mount.
    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
    });

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });

    // Watch ran (full fetch of the finished local sub-agent)…
    expect(mockFn(getAiRequest)).toHaveBeenCalled();
    const fetchCall = mockFn(getAiRequest).mock.calls.find(
      call => call[1] && call[1].aiRequestId === 'local-ai-sub-1'
    );
    expect(fetchCall).toBeTruthy();
    if (fetchCall) {
      expect(fetchCall[1].userId).toBe('local-byok-user');
    }
    // …and the finished child was retired because the parent already carries
    // its function_call_output.
    // $FlowFixMe[incompatible-use]
    expect(contextRef.current.activeSubAgents).toEqual({});
  });

  it('watches local-ai-* sub-agents when logged out even with the custom endpoint disabled', async () => {
    // Cycle 66: local-ai-* ids are cache-only — the endpoint toggle must not
    // gate the watch (getAiRequest short-circuits on the local-ai- prefix).
    setCustomEndpointConfig({
      enabled: false,
      baseUrl: 'http://localhost:11434/v1',
      apiKey: '',
      model: 'qwen2.5-coder',
      temperature: 0.7,
    });
    const { contextRef } = renderProvider(makeLoggedOutUser());
    if (!contextRef.current) throw new Error('Context not captured');

    const parentWithOutput = {
      ...makeAiRequest('parent-1', 'ready'),
      output: [
        {
          type: 'function_call_output',
          call_id: 'call-1',
          output: 'done',
        },
      ],
    };
    const subReady = makeAiRequest('local-ai-sub-1', 'ready');
    mockFn(getAiRequest).mockResolvedValue(subReady);

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'parent-1',
        () => parentWithOutput
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'local-ai-sub-1',
        () => subReady
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent(
        'local-ai-sub-1',
        'parent-1',
        'call-1'
      );
    });

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });

    const fetchCall = mockFn(getAiRequest).mock.calls.find(
      call => call[1] && call[1].aiRequestId === 'local-ai-sub-1'
    );
    expect(fetchCall).toBeTruthy();
    if (fetchCall) {
      expect(fetchCall[1].userId).toBe('local-byok-user');
    }
    // Hosted ids are never addressed without a profile: only the local call ran.
    const hostedCall = mockFn(getAiRequest).mock.calls.find(
      call => call[1] && !String(call[1].aiRequestId).startsWith('local-ai-')
    );
    expect(hostedCall).toBeFalsy();
    // $FlowFixMe[incompatible-use]
    expect(contextRef.current.activeSubAgents).toEqual({});
  });
});

describe('mergeIncrementalAiRequest', () => {
  const message = (messageId: string) => ({
    messageId,
    type: 'message',
    status: 'completed',
    role: 'user',
    content: [{ type: 'user_request', status: 'completed', text: messageId }],
  });
  const requestWithOutput = (output: Array<any>): AiRequest => ({
    ...makeAiRequest('req-1', 'working'),
    output,
  });

  it('returns the fetched request as-is when there is no outputFromMessageId', () => {
    const fetched = requestWithOutput([message('a'), message('b')]);
    expect(
      mergeIncrementalAiRequest(
        requestWithOutput([message('a')]),
        fetched,
        undefined
      )
    ).toBe(fetched);
  });

  it('splices the incremental slice onto the cached output', () => {
    const previous = requestWithOutput([message('a'), message('b')]);
    // The backend re-sends the tail ('b') plus the new message ('c').
    const fetched = requestWithOutput([message('b'), message('c')]);
    const merged = mergeIncrementalAiRequest(previous, fetched, 'b');
    const mergedOutput = merged.output || [];
    const fetchedOutput = fetched.output || [];

    expect(mergedOutput.map(m => m.messageId)).toEqual(['a', 'b', 'c']);
    // The tail is taken from the fetched response (so in-place updates like
    // suggestions are picked up), not from the cache.
    expect(mergedOutput[1]).toBe(fetchedOutput[0]);
  });

  it('does not throw when the fetched first message is not an object', () => {
    // `output[0]` is network-supplied and getAiRequest validates only the
    // request's `id` key, so reading `.messageId` off a null entry threw out of
    // the polling loop.
    const previous = requestWithOutput([message('a')]);
    for (const bad of [null, undefined, 'text', 42]) {
      const fetched = requestWithOutput([(bad: any), message('b')]);
      expect(mergeIncrementalAiRequest(previous, fetched, 'a')).toBe(fetched);
    }
  });

  it('returns the fetched request as-is when it is a full output, not a slice', () => {
    const previous = requestWithOutput([message('a'), message('b')]);
    const fetched = requestWithOutput([
      message('a'),
      message('b'),
      message('c'),
    ]);
    expect(mergeIncrementalAiRequest(previous, fetched, 'b')).toBe(fetched);
  });
});

describe('useAiRequestHistory', () => {
  const userMessage = (text: string): AiRequestUserMessage => ({
    type: 'message',
    status: 'completed',
    role: 'user',
    content: [{ type: 'user_request', status: 'completed', text }],
  });

  const requestWithUserMessages = (
    id: string,
    updatedAt: string,
    texts: Array<string>,
    parentAiRequestId?: string | null
  ): AiRequest => ({
    ...makeAiRequest(id, 'ready', parentAiRequestId),
    updatedAt,
    output: texts.map(userMessage),
  });

  const renderHistoryHook = (aiRequests: { [string]: AiRequest }) => {
    const hookResultRef: { current: any } = { current: null };
    const aiRequestSummaries: { [string]: AiRequestSummary } = {};
    Object.keys(aiRequests).forEach(aiRequestId => {
      aiRequestSummaries[aiRequestId] = getAiRequestSummary(
        aiRequests[aiRequestId]
      );
    });
    const HookCapture = () => {
      hookResultRef.current = useAiRequestHistory(
        ({ aiRequests, aiRequestSummaries }: any)
      );
      return null;
    };
    act(() => {
      TestRenderer.create(<HookCapture />);
    });
    return hookResultRef;
  };

  const navigateUp = (hookResultRef: { current: any }) => {
    let latestText = '';
    act(() => {
      hookResultRef.current.handleNavigateHistory({
        direction: 'up',
        currentText: '',
        onChangeText: text => {
          latestText = text;
        },
      });
    });
    return latestText;
  };

  it('browses the first message of each conversation, from the most recent', () => {
    const hookResultRef = renderHistoryHook({
      'chat-1': requestWithUserMessages('chat-1', '2024-01-01T00:00:00.000Z', [
        'Make a platformer game',
        'A second message, which the summary does not carry',
      ]),
      'chat-2': requestWithUserMessages('chat-2', '2024-01-01T00:02:00.000Z', [
        'Add coins to collect',
      ]),
      'chat-3': requestWithUserMessages('chat-3', '2024-01-01T00:01:00.000Z', [
        'Make the player jump',
      ]),
    });

    expect(navigateUp(hookResultRef)).toBe('Add coins to collect');
    expect(navigateUp(hookResultRef)).toBe('Make the player jump');
    expect(navigateUp(hookResultRef)).toBe('Make a platformer game');
    // No more history.
    expect(navigateUp(hookResultRef)).toBe('');
  });
});

describe('AiRequestProvider opening a chat from the history', () => {
  // The provider is unmounted after each test: its timers (polling, settings
  // fetch) must not outlive the test, or Jest would not exit.
  let renderer = null;
  const renderProviderToUnmount = () => {
    const rendered = renderProvider();
    renderer = rendered.renderer;
    return rendered.contextRef;
  };

  beforeEach(() => {
    jest.useFakeTimers();
    mockFn(getAiRequest).mockReset();
    mockFn(suspendAiRequest).mockReset();
    mockFn(getAiRequestStatuses).mockReset();
    mockFn(getAiRequestStatuses).mockResolvedValue([]);
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequestSummaries).mockReset();
    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [],
      nextPageUri: null,
    });
    mockFn(apiUpdateAiRequest).mockReset();
    // Hosted-style resolution: archive re-reads archivedAt from the response.
    mockFn(apiUpdateAiRequest).mockImplementation(
      async (
        _getAuth: any,
        params: {|
          aiRequestId: string,
          title?: string | null,
          archived?: boolean,
        |}
      ) => ({
        ...makeAiRequest(params.aiRequestId, 'ready'),
        title: params.title !== undefined ? params.title : undefined,
        archivedAt: params.archived
          ? '2024-06-01T00:00:00.000Z'
          : params.archived === false
          ? null
          : undefined,
      })
    );
    mockFn(apiDeleteAiRequest).mockReset();
    mockFn(apiDeleteAiRequest).mockResolvedValue(undefined);
  });

  afterEach(() => {
    act(() => {
      if (renderer) renderer.unmount();
    });
    renderer = null;
    jest.useRealTimers();
  });

  const getContext = (contextRef: {
    current: AiRequestContextState | null,
  }): AiRequestContextState => {
    if (!contextRef.current) throw new Error('Context not captured');
    return contextRef.current;
  };

  it('selects the chat immediately and loads it', async () => {
    const contextRef = renderProviderToUnmount();
    const aiRequest = makeAiRequest('chat-1', 'ready');
    mockFn(getAiRequest).mockResolvedValue(aiRequest);

    act(() => {
      getContext(contextRef).setSelectedAiRequestId('chat-1');
    });
    // Selected right away, with its conversation being loaded.
    expect(getContext(contextRef).selectedAiRequestId).toBe('chat-1');
    expect(getContext(contextRef).selectedAiRequest).toBe(null);
    expect(
      getContext(contextRef).aiRequestStorage.aiRequestLoadingStates['chat-1']
    ).toEqual({ isLoading: true, error: null });

    await act(async () => {
      await flushPromises();
    });
    expect(getContext(contextRef).selectedAiRequest).toEqual(aiRequest);
    expect(
      getContext(contextRef).aiRequestStorage.aiRequestLoadingStates['chat-1']
    ).toBeUndefined();
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);
    expect(mockFn(suspendAiRequest)).not.toHaveBeenCalled();
    // The loaded chat is listed in the history.
    expect(
      getContext(contextRef).aiRequestStorage.aiRequestSummaries['chat-1']
    ).toEqual(getAiRequestSummary(aiRequest));
  });

  it('does not load a chat already in memory', async () => {
    const contextRef = renderProviderToUnmount();
    const aiRequest = makeAiRequest('chat-1', 'ready');
    act(() => {
      getContext(contextRef).aiRequestStorage.updateAiRequest(
        'chat-1',
        () => aiRequest
      );
    });

    act(() => {
      getContext(contextRef).setSelectedAiRequestId('chat-1');
    });
    await act(async () => {
      await flushPromises();
    });
    expect(getContext(contextRef).selectedAiRequest).toEqual(aiRequest);
    expect(mockFn(getAiRequest)).not.toHaveBeenCalled();
  });

  it('suspends a local BYOK request without touching the hosted API', async () => {
    const contextRef = renderProviderToUnmount();
    const workingLocalRequest = makeAiRequest('local-ai-test-1', 'working');
    act(() => {
      getContext(contextRef).aiRequestStorage.updateAiRequest(
        'local-ai-test-1',
        () => workingLocalRequest
      );
    });

    await act(async () => {
      await getContext(contextRef).suspendAiRequest('local-ai-test-1');
      await flushPromises();
    });

    expect(mockFn(suspendAiRequest)).not.toHaveBeenCalled();
    // The local cache copy is suspended (which also aborts its model turn).
    expect(customGetAiRequest('local-ai-test-1').status).toBe('suspended');
    // The client was invoked so its in-flight turn gets cancelled.
    expect(customGetAiRequest('local-ai-test-1').id).toBe('local-ai-test-1');
  });

  it('suspends a chat left with work in progress before opening it', async () => {
    const contextRef = renderProviderToUnmount();
    const workingAiRequest = makeAiRequest('chat-1', 'working');
    const suspendedAiRequest = makeAiRequest('chat-1', 'suspended');
    mockFn(getAiRequest).mockResolvedValue(workingAiRequest);
    mockFn(suspendAiRequest).mockResolvedValue(suspendedAiRequest);

    act(() => {
      getContext(contextRef).setSelectedAiRequestId('chat-1');
    });
    await act(async () => {
      await flushPromises();
    });
    expect(mockFn(suspendAiRequest)).toHaveBeenCalledTimes(1);
    expect(getContext(contextRef).selectedAiRequest).toEqual(
      suspendedAiRequest
    );
  });

  it('does not call the hosted suspend API for a non-local id when logged out', async () => {
    const { contextRef } = renderProvider(makeLoggedOutUser());
    if (!contextRef.current) throw new Error('Context not captured');

    mockFn(suspendAiRequest).mockClear();
    const hostedRequest = makeAiRequest('chat-hosted-1', 'working');
    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'chat-hosted-1',
        () => hostedRequest
      );
    });

    await act(async () => {
      await getContext(contextRef).suspendAiRequest('chat-hosted-1');
    });

    // Empty-string userIds must never reach the Generation suspend endpoint.
    expect(mockFn(suspendAiRequest)).not.toHaveBeenCalled();
  });

  it('renames a hosted id without a profile without calling the hosted API', async () => {
    const { contextRef } = renderProvider(makeLoggedOutUser());
    if (!contextRef.current) throw new Error('Context not captured');

    mockFn(apiUpdateAiRequest).mockClear();
    const hostedSummary = {
      ...makeAiRequest('chat-hosted-2', 'ready'),
      title: 'Hosted chat',
      archivedAt: null,
    };
    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'chat-hosted-2',
        () => hostedSummary
      );
    });

    await act(async () => {
      await getContext(contextRef).aiRequestStorage.renameAiRequest(
        'chat-hosted-2',
        'Renamed while logged out'
      );
    });

    expect(mockFn(apiUpdateAiRequest)).not.toHaveBeenCalled();
  });

  it('keeps a loading error until the user retries', async () => {
    const contextRef = renderProviderToUnmount();
    mockFn(getAiRequest).mockRejectedValue(new Error('Network error'));

    act(() => {
      getContext(contextRef).setSelectedAiRequestId('chat-1');
    });
    await act(async () => {
      await flushPromises();
    });
    expect(getContext(contextRef).selectedAiRequest).toBe(null);
    const loadingState = getContext(contextRef).aiRequestStorage
      .aiRequestLoadingStates['chat-1'];
    expect(loadingState.isLoading).toBe(false);
    expect(loadingState.error).toBeInstanceOf(Error);
    // No automatic retry.
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);

    const aiRequest = makeAiRequest('chat-1', 'ready');
    mockFn(getAiRequest).mockResolvedValue(aiRequest);
    await act(async () => {
      await getContext(contextRef).aiRequestStorage.loadAiRequest('chat-1');
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(2);
    expect(getContext(contextRef).selectedAiRequest).toEqual(aiRequest);
    expect(
      getContext(contextRef).aiRequestStorage.aiRequestLoadingStates['chat-1']
    ).toBeUndefined();
  });

  it('renames and archives a local BYOK request without touching a remote id', async () => {
    const contextRef = renderProviderToUnmount();
    const localRequest = makeAiRequest('local-ai-rename-1', 'ready');
    const storage = () => getContext(contextRef).aiRequestStorage;
    act(() => {
      storage().updateAiRequest('local-ai-rename-1', () => localRequest);
    });

    await act(async () => {
      await storage().renameAiRequest('local-ai-rename-1', 'Local chat');
      await flushPromises();
    });

    expect(mockFn(apiUpdateAiRequest)).toHaveBeenCalledTimes(1);
    expect(mockFn(apiUpdateAiRequest).mock.calls[0][1].aiRequestId).toBe(
      'local-ai-rename-1'
    );
    expect(mockFn(apiUpdateAiRequest).mock.calls[0][1].title).toBe(
      'Local chat'
    );

    await act(async () => {
      await storage().setAiRequestArchived('local-ai-rename-1', true);
      await flushPromises();
    });
    expect(mockFn(apiUpdateAiRequest)).toHaveBeenCalledTimes(2);
    expect(mockFn(apiUpdateAiRequest).mock.calls[1][1].archived).toBe(true);
    expect(mockFn(apiUpdateAiRequest).mock.calls[1][1].aiRequestId).toBe(
      'local-ai-rename-1'
    );
  });

  it('deletes a local BYOK request and removes it from history state', async () => {
    const contextRef = renderProviderToUnmount();
    const localRequest = makeAiRequest('local-ai-del-1', 'ready');
    act(() => {
      getContext(contextRef).aiRequestStorage.updateAiRequest(
        'local-ai-del-1',
        () => localRequest
      );
    });

    await act(async () => {
      await getContext(contextRef).aiRequestStorage.deleteAiRequest(
        'local-ai-del-1'
      );
      await flushPromises();
    });

    // Generation is mocked here: the call is recorded with the local id.
    // Hosted-API routing for local-ai-* is covered by Generation.spec.js.
    expect(mockFn(apiDeleteAiRequest)).toHaveBeenCalledTimes(1);
    expect(mockFn(apiDeleteAiRequest).mock.calls[0][1].aiRequestId).toBe(
      'local-ai-del-1'
    );
    expect(
      getContext(contextRef).aiRequestStorage.aiRequests['local-ai-del-1']
    ).toBeUndefined();
    expect(
      getContext(contextRef).aiRequestStorage.aiRequestSummaries[
        'local-ai-del-1'
      ]
    ).toBeUndefined();
  });
});

describe('AiRequestProvider history reload after logout', () => {
  beforeEach(() => {
    mockFn(getAiRequest).mockReset();
    mockFn(getAiRequestStatuses).mockReset();
    mockFn(getAiRequestStatuses).mockResolvedValue([]);
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequestSummaries).mockReset();
    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [],
      nextPageUri: null,
    });
    // Endpoint off: the old early-return skipped the summary fetch entirely,
    // so local chats vanished from the history after logout.
    setCustomEndpointConfig({
      enabled: false,
      baseUrl: 'http://localhost:11434/v1',
      apiKey: '',
      model: 'qwen2.5-coder',
      temperature: 0.7,
    });
  });

  afterEach(() => {
    setCustomEndpointConfig({
      enabled: false,
      baseUrl: 'http://localhost:11434/v1',
      apiKey: '',
      model: 'qwen2.5-coder',
      temperature: 0.7,
    });
  });

  it('fetches local summaries when the provider mounts logged out without a custom endpoint', async () => {
    const localSummary = {
      id: 'local-ai-after-logout',
      title: 'Local chat',
      archivedAt: null,
      gameId: null,
      createdAt: '2024-06-01T00:00:00.000Z',
      updatedAt: '2024-06-01T00:00:00.000Z',
      userId: 'local-byok-user',
      status: 'ready',
      mode: 'chat',
      error: null,
      output: [],
    };
    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [localSummary],
      nextPageUri: null,
    });

    const { contextRef } = renderProvider(makeLoggedOutUser());
    await act(async () => {
      await flushPromises();
    });

    expect(mockFn(getAiRequestSummaries)).toHaveBeenCalled();
    const call = mockFn(getAiRequestSummaries).mock.calls[0];
    expect(call[1].userId).toBe('local-byok-user');
    // $FlowFixMe[incompatible-use]
    expect(
      contextRef.current.aiRequestStorage.aiRequestSummaries[
        'local-ai-after-logout'
      ]
    ).toBeTruthy();
  });

  it('clears hosted chats on logout then reloads local summaries', async () => {
    // Start authenticated with a hosted summary already in state.
    const hostedSummary = {
      id: 'hosted-1',
      title: 'Hosted chat',
      archivedAt: null,
      gameId: null,
      createdAt: '2024-06-01T00:00:00.000Z',
      updatedAt: '2024-06-01T00:00:00.000Z',
      userId: 'user-1',
      status: 'ready',
      mode: 'chat',
      error: null,
      output: [],
    };
    const localSummary = {
      ...hostedSummary,
      id: 'local-ai-keep',
      userId: 'local-byok-user',
    };

    let setUser;
    const SwitchableUser = () => {
      const [user, setNextUser] = React.useState(makeAuthenticatedUser());
      setUser = setNextUser;
      return (
        <AuthenticatedUserContext.Provider value={user}>
          <AiRequestProvider>
            <ContextCapture contextRef={capturedRef} />
          </AiRequestProvider>
        </AuthenticatedUserContext.Provider>
      );
    };
    const capturedRef: { current: AiRequestContextState | null } = {
      current: null,
    };

    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [hostedSummary],
      nextPageUri: null,
    });

    let renderer;
    act(() => {
      renderer = TestRenderer.create(<SwitchableUser />);
    });
    await act(async () => {
      await flushPromises();
    });
    if (!capturedRef.current) throw new Error('Context not captured');
    // Authenticated mount does not auto-fetch history (the Ask AI pane does);
    // seed it the same way the pane would.
    await act(async () => {
      await capturedRef.current.aiRequestStorage.fetchAiRequestSummaries();
      await flushPromises();
    });
    expect(
      capturedRef.current.aiRequestStorage.aiRequestSummaries['hosted-1']
    ).toBeTruthy();

    // After logout, summaries come from the local cache only.
    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [localSummary],
      nextPageUri: null,
    });
    await act(async () => {
      if (!setUser) throw new Error('setUser not ready');
      setUser(makeLoggedOutUser());
      await flushPromises();
    });

    expect(mockFn(getAiRequestSummaries).mock.calls.length).toBeGreaterThan(1);
    const lastCall = mockFn(getAiRequestSummaries).mock.calls[
      mockFn(getAiRequestSummaries).mock.calls.length - 1
    ];
    expect(lastCall[1].userId).toBe('local-byok-user');
    if (!capturedRef.current) throw new Error('Context not captured');
    // Hosted chats were wiped; the reloaded local chat is present.
    expect(
      capturedRef.current.aiRequestStorage.aiRequestSummaries['hosted-1']
    ).toBeUndefined();
    expect(
      capturedRef.current.aiRequestStorage.aiRequestSummaries['local-ai-keep']
    ).toBeTruthy();
    if (renderer) renderer.unmount();
  });
});
