// @flow
import * as React from 'react';
import TestRenderer from 'react-test-renderer';
import { act } from 'react-dom/test-utils';
import {
  getAiRequest,
  getAiRequestStatuses,
  fetchAiSettings,
  getAiRequestSummaries,
  suspendAiRequest,
  type AiRequest,
} from '../Utils/GDevelopServices/Generation';
import AuthenticatedUserContext, {
  initialAuthenticatedUser,
  type AuthenticatedUser,
} from '../Profile/AuthenticatedUserContext';
import {
  AiRequestContext,
  AiRequestProvider,
  type AiRequestContextState,
} from './AiRequestContext';
import { useAiRequestState } from './Utils';

// Utils.js transitively imports Pixi/Spine/three ESM packages that Jest cannot
// parse. useAiRequestState itself does not need those editor/asset modules.
jest.mock('../EditorFunctions/EditorFunctionCallRunner', () => ({
  processEditorFunctionCalls: jest.fn(),
}));
jest.mock('../EditorFunctions', () => ({
  editorFunctions: {},
  editorFunctionsWithoutProject: {},
}));
jest.mock('./UseSearchAndInstallAsset', () => ({
  useSearchAndInstallAsset: jest.fn(() => ({
    searchAndInstallAsset: jest.fn(),
  })),
}));
jest.mock('./UseSearchAndInstallResource', () => ({
  useSearchAndInstallResources: jest.fn(() => ({
    searchAndInstallResources: jest.fn(),
  })),
}));
jest.mock('./UseGenerateEvents', () => ({
  useGenerateEvents: jest.fn(() => ({
    generateEvents: jest.fn(),
  })),
}));
jest.mock('./UseEnsureExtensionInstalled', () => ({
  useEnsureExtensionInstalled: jest.fn(() => ({
    ensureExtensionInstalled: jest.fn(),
  })),
}));

jest.mock('../Utils/GDevelopServices/Generation', () => ({
  ...jest.genMockFromModule('../Utils/GDevelopServices/Generation'),
  getAiRequestSummary: jest.requireActual<any>(
    '../Utils/GDevelopServices/Generation'
  ).getAiRequestSummary,
}));

const mockFn = (fn: any): JestMockFn<any, any> => fn;

const makeAiRequest = (id: string, status: 'working' | 'ready'): AiRequest => ({
  id,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  userId: 'user-1',
  status,
  error: null,
  output: [],
  parentAiRequestId: null,
});

const makeAuthenticatedUser = (): AuthenticatedUser => ({
  ...initialAuthenticatedUser,
  authenticated: true,
  profile: {
    id: 'user-1',
    email: 'fake@example.com',
    username: 'fake-user',
    isEmailAutogenerated: false,
    description: '',
    getGameStatsEmail: false,
    getNewsletterEmail: false,
    isCreator: false,
    isPlayer: false,
    appLanguage: 'en',
    donateLink: null,
    discordUsername: null,
    communityLinks: {},
    createdAt: 0,
    updatedAt: 0,
  },
  loginState: 'done',
  getAuthorizationHeader: () => Promise.resolve('fake-auth-header'),
});

const ContextCapture = ({
  contextRef,
}: {|
  contextRef: { current: AiRequestContextState | null },
|}) => {
  const context = React.useContext(AiRequestContext);
  contextRef.current = context;
  return null;
};

// Mounts useAiRequestState the same way AskAiEditorContainer does, so a
// second selection-load effect would race AiRequestProvider's loadAiRequest.
const AiRequestStateProbe = () => {
  useAiRequestState({ project: null });
  return null;
};

const flushPromises = async () => {
  for (let i = 0; i < 10; i++) {
    // eslint-disable-next-line no-await-in-loop
    await Promise.resolve();
  }
};

const getContext = (contextRef: {
  current: AiRequestContextState | null,
}): AiRequestContextState => {
  if (!contextRef.current) throw new Error('Context not captured');
  return contextRef.current;
};

const renderProviderWithAiRequestState = () => {
  const contextRef: { current: AiRequestContextState | null } = {
    current: null,
  };
  let renderer;
  act(() => {
    renderer = TestRenderer.create(
      <AuthenticatedUserContext.Provider value={makeAuthenticatedUser()}>
        <AiRequestProvider>
          <ContextCapture contextRef={contextRef} />
          <AiRequestStateProbe />
        </AiRequestProvider>
      </AuthenticatedUserContext.Provider>
    );
  });
  return { contextRef, renderer };
};

describe('selection load with useAiRequestState mounted', () => {
  let renderer = null;

  beforeEach(() => {
    jest.useFakeTimers();
    mockFn(getAiRequest).mockReset();
    mockFn(suspendAiRequest).mockReset();
    mockFn(getAiRequestStatuses).mockReset();
    mockFn(getAiRequestStatuses).mockResolvedValue([]);
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequestSummaries).mockReset();
    mockFn(getAiRequestSummaries).mockResolvedValue({
      aiRequestSummaries: [],
      nextPageUri: null,
    });
  });

  afterEach(() => {
    act(() => {
      if (renderer) renderer.unmount();
    });
    renderer = null;
    jest.useRealTimers();
  });

  it('loads a chat exactly once when a profile is present', async () => {
    // Regression: useAiRequestState used to re-fetch the selected chat when a
    // profile was present, racing AiRequestProvider's loadAiRequest effect.
    const rendered = renderProviderWithAiRequestState();
    renderer = rendered.renderer;
    const contextRef = rendered.contextRef;

    const aiRequest = makeAiRequest('chat-1', 'ready');
    mockFn(getAiRequest).mockResolvedValue(aiRequest);

    act(() => {
      getContext(contextRef).setSelectedAiRequestId('chat-1');
    });
    await act(async () => {
      await flushPromises();
    });

    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);
    expect(getContext(contextRef).selectedAiRequest).toEqual(aiRequest);
    expect(
      getContext(contextRef).aiRequestStorage.aiRequestLoadingStates['chat-1']
    ).toBeUndefined();
  });

  it('keeps the selection when loading fails', async () => {
    // Regression: useAiRequestState used to clear selectedAiRequestId on a
    // failed secondary fetch, fighting the provider's retry UI.
    const rendered = renderProviderWithAiRequestState();
    renderer = rendered.renderer;
    const contextRef = rendered.contextRef;

    mockFn(getAiRequest).mockRejectedValue(new Error('Network error'));
    act(() => {
      getContext(contextRef).setSelectedAiRequestId('chat-1');
    });
    await act(async () => {
      await flushPromises();
    });

    expect(getContext(contextRef).selectedAiRequestId).toBe('chat-1');
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);
    const loadingState = getContext(contextRef).aiRequestStorage
      .aiRequestLoadingStates['chat-1'];
    expect(loadingState.isLoading).toBe(false);
    expect(loadingState.error).toBeInstanceOf(Error);
  });
});
